export const CHAT_INTENTS = [
  "greeting",
  "farewell",
  "small_talk",
  "checking_in",
  "silence_acknowledgment",
  "how_are_you",
  "expressing_boredom",
  "expressing_sadness",
  "expressing_anger",
  "expressing_excitement",
  "expressing_confusion",
  "expressing_stress",
  "expressing_loneliness",
  "about_self",
  "ask_name",
  "ask_age",
  "ask_location",
  "ask_occupation",
  "ask_hobbies",
  "ask_preferences",
  "thanks",
  "compliment",
  "insult",
  "flirting",
  "expressing_affection",
  "apology",
  "forgiveness",
  "agreement",
  "disagreement",
  "ask_for_clarification",
  "ask_to_repeat",
  "change_topic",
  "interrupting",
  "general_question",
  "ask_opinion",
  "ask_for_advice",
  "ask_for_recommendation",
  "rhetorical_question",
  "sharing_personal_story",
  "sharing_daily_routine",
  "bot_accusation",
  "turing_test",
  "ask_capabilities",
  "privacy_concern",
  "comment_on_response_time",
  "chat_invite",
  "ask_for_contact_info",
  "ask_for_favor",
  "ask_for_money",
  "gift_giving",
  "gift_receiving",
  "tell_joke",
  "react_to_joke",
  "sarcasm",
  "playful_teasing",
  "ask_time",
  "ask_date",
  "comment_on_weather",
  "nonsense",
  "spam",
  "inappropriate_content",
  "language_switch",
  "typo_correction",
  "small_talk",
] as const;

export type ChatIntent = (typeof CHAT_INTENTS)[number];

export const PROFILE_INTENTS: readonly ChatIntent[] = [
  "about_self",
  "ask_name",
  "ask_age",
  "ask_location",
  "ask_occupation",
  "ask_hobbies",
  "ask_preferences",
];

export const VALID_INTENTS = new Set<string>(CHAT_INTENTS);
