export const SEED_BOTS = [
  {
    socketId: "kR7mN2pQx9vL4wHj8sTf",
    nickname: "Маша",
    characterType: "cat",
    gender: "female",
    eyeColor: "#8E44AD",
    equipped: {
      hats: { itemId: "crown_gold", color: null },
      bottom: { itemId: "bottom_baggy", color: "#e91e63" },
    },
    ownedItems: ["crown_gold", "bottom_baggy"],
    coins: 210,
    inventoryValue: 110,
    status: "",
    badges: ["messages_10"],
    anketa_about: "Слушаю музыку по ночам, люблю длинные прогулки",
    anketa_city: "Спб",
    anketa_interests: "Музыка, природа, фотография",
    anketa_age: "16",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Спешу", "Не беспокоить", "Ок", "Скучаю", "Тут", "Думаю"],
  },
  {
    socketId: "bW3nK8rTy5mP1vQc6xLd",
    nickname: "Liza",
    characterType: "fox",
    gender: "female",
    eyeColor: "#E74C3C",
    equipped: { shoes: { itemId: "shoes_converse", color: "#c62828" } },
    ownedItems: ["shoes_converse"],
    coins: 130,
    inventoryValue: 30,
    status: "",
    badges: ["first_message"],
    anketa_about: "Пишу стихи когда грустно, читаю классику",
    anketa_city: "Мск",
    anketa_interests: "Литература, ночь, кино",
    anketa_age: "17",
    statusPool: [
      "",
      "Afk",
      "Читаю",
      "Не беспокоить",
      "Скучно",
      "Brb",
    ],
  },
  {
    socketId: "pL9vH4mNx2Qw7kRs3jYf",
    nickname: "Аня",
    characterType: "panda",
    gender: "female",
    eyeColor: "#3498DB",
    equipped: {
      hats: { itemId: "hat_cpcompany", color: "#607d8b" },
      bottom: { itemId: "bottom_baggy", color: "#1565c0" },
    },
    ownedItems: ["hat_cpcompany", "bottom_baggy"],
    coins: 190,
    inventoryValue: 95,
    status: "",
    badges: ["messages_10", "first_friend"],
    anketa_about: "Люблю конкурсы викторин, изучаю интересные факты",
    anketa_city: "Екб",
    anketa_interests: "Наука, квизы, загадки",
    anketa_age: "15",
    statusPool: [
      "",
      "Учусь",
      "Залипаю",
      "Тут",
      "В диване",
      "Скучаюуу",
    ],
  },
  {
    socketId: "mT6wQ1nKx8Rv4pLc9sHj",
    nickname: "Vera",
    characterType: "raccoon",
    gender: "female",
    eyeColor: "#27AE60",
    equipped: { shoes: { itemId: "shoes_sneakers", color: null } },
    ownedItems: ["shoes_sneakers"],
    coins: 80,
    inventoryValue: 40,
    status: "",
    badges: [],
    anketa_about: "Молчаливая, но могу говорить часами о том что интересует",
    anketa_city: "Новосиб",
    anketa_interests: "Философия, чай, книги",
    anketa_age: "18",
    statusPool: [
      "",
      "Валяюсь",
      "Чай",
      "Не тревожить",
      "Думаю",
      "Может позже",
    ],
  },
  {
    socketId: "vN2pK7wRx5mL9qTc4jHs",
    nickname: "Таня",
    characterType: "dog",
    gender: "female",
    eyeColor: "#F39C12",
    equipped: { shoes: { itemId: "shoes_boots", color: "#5d4037" } },
    ownedItems: ["shoes_boots"],
    coins: 65,
    inventoryValue: 35,
    status: "",
    badges: ["first_message"],
    anketa_about: "Люблю гулять одна, находить тихие места",
    anketa_city: "Казань",
    anketa_interests: "Искусство, прогулки, архитектура",
    anketa_age: "14",
    statusPool: ["", "Гуляю", "Рисую", "Устала", "Тут", "Скучно"],
  },
  {
    socketId: "aA1bB2cC3dD4eE5fF6gG",
    nickname: "Artym",
    characterType: "dog",
    gender: "male",
    eyeColor: "#2C3E50",
    equipped: { hats: { itemId: "hat_cap", color: "#000000" } },
    ownedItems: ["hat_cap"],
    coins: 240,
    inventoryValue: 120,
    status: "",
    badges: ["messages_10"],
    anketa_about: "Слушаю всякое по ночам, не сплю вообще",
    anketa_city: "Мск",
    anketa_interests: "Музыка, фильмы, мемы",
    anketa_age: "17",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Не сплю", "Слушаю", "Не трогать", "В сети", "Ночной"],
  },
  {
    socketId: "hH7iI8jJ9kK0lL1mM2nN",
    nickname: "Maria",
    characterType: "cat",
    gender: "female",
    eyeColor: "#8B4513",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#8B4513" } },
    ownedItems: ["bottom_baggy"],
    coins: 145,
    inventoryValue: 45,
    status: "",
    badges: ["first_friend"],
    anketa_about: "Жду когда закончится эта учеба, люблю выходные",
    anketa_city: "Спб",
    anketa_interests: "Развлечения, друзья, интернет",
    anketa_age: "16",
    anketa_looking_for: "Друзья по интересам",
    statusPool: ["", "Читаю", "В интернете", "Скучаю", "Не знаю", "Может быть"],
  },
  {
    socketId: "oO3pP4qQ5rR6sS7tT8uU",
    nickname: "Лев",
    characterType: "raccoon",
    gender: "male",
    eyeColor: "#1E90FF",
    equipped: { shoes: { itemId: "shoes_sneakers", color: "#1E90FF" } },
    ownedItems: ["shoes_sneakers"],
    coins: 320,
    inventoryValue: 150,
    status: "",
    badges: ["messages_10", "first_message"],
    anketa_about: "Сидю в интернете, тот еще ночной жаворонок",
    anketa_city: "Новосиб",
    anketa_interests: "Компьютеры, технологии, всякое",
    anketa_age: "18",
    anketa_looking_for: "Свои люди",
    statusPool: ["", "Онлайн", "В чате", "Помогаю", "Общаюсь", "Ночь"],
  },
  {
    socketId: "vV9wW0xX1yY2zZ3aA4bB",
    nickname: "Sonya",
    characterType: "fox",
    gender: "female",
    eyeColor: "#E91E63",
    equipped: {
      hats: { itemId: "hat_beanie", color: "#FFB6C1" },
      shoes: { itemId: "shoes_boots", color: "#FFB6C1" },
    },
    ownedItems: ["hat_beanie", "shoes_boots"],
    coins: 200,
    inventoryValue: 100,
    status: "",
    badges: ["first_message"],
    anketa_about: "Забуду про время когда чем-то увлекаюсь",
    anketa_city: "Казань",
    anketa_interests: "Творчество, аниме, фантазии",
    anketa_age: "15",
    anketa_looking_for: "Друзья",
    statusPool: ["", "В деле", "Сосредоточена", "Идея!", "Вдохновение", "Не трогайте"],
  },
  {
    socketId: "cC5dD6eE7fF8gG9hH0iI",
    nickname: "Миша",
    characterType: "dog",
    gender: "male",
    eyeColor: "#4CAF50",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#4CAF50" } },
    ownedItems: ["bottom_baggy"],
    coins: 175,
    inventoryValue: 65,
    status: "",
    badges: [],
    anketa_about: "Люблю быть в движении, не могу просто сидеть",
    anketa_city: "Владивосток",
    anketa_interests: "Спорт, активность, приключения",
    anketa_age: "17",
    anketa_looking_for: "Компания",
    statusPool: ["", "Движение", "Активный", "Пляж", "Давайте", "Да"],
  },
  {
    socketId: "jJ1kK2lL3mM4nN5oO6pP",
    nickname: "Kira",
    characterType: "fox",
    gender: "female",
    eyeColor: "#FF6347",
    equipped: { hats: { itemId: "hat_cpcompany", color: "#FF6347" } },
    ownedItems: ["hat_cpcompany"],
    coins: 280,
    inventoryValue: 130,
    status: "",
    badges: ["messages_10", "first_friend"],
    anketa_about: "Рассказываю что вижу и чувствую, люблю беседовать",
    anketa_city: "Мск",
    anketa_interests: "Люди, истории, впечатления",
    anketa_age: "19",
    anketa_looking_for: "Знакомства",
    statusPool: ["", "Говорю", "Слушаю", "Интересно", "Не знаю", "Рассказываю"],
  },
  {
    socketId: "qQ7rR8sS9tT0uU1vV2wW",
    nickname: "Даша",
    characterType: "cat",
    gender: "female",
    eyeColor: "#DDA0DD",
    equipped: {
      bottom: { itemId: "bottom_baggy", color: "#DDA0DD" },
      shoes: { itemId: "shoes_sneakers", color: "#DDA0DD" },
    },
    ownedItems: ["bottom_baggy", "shoes_sneakers"],
    coins: 190,
    inventoryValue: 85,
    status: "",
    badges: ["first_message"],
    anketa_about: "Делаю свое, слушаю себя больше чем других",
    anketa_city: "Спб",
    anketa_interests: "Стиль, себя, выражение",
    anketa_age: "16",
    anketa_looking_for: "Своих",
    statusPool: ["", "Занята", "Отключена", "Не сейчас", "Потом", "Может быть"],
  },
  {
    socketId: "xX3yY4zZ5aA6bB7cC8dD",
    nickname: "Egor",
    characterType: "panda",
    gender: "male",
    eyeColor: "#FFD700",
    equipped: { hats: { itemId: "hat_cap", color: "#FFD700" } },
    ownedItems: ["hat_cap"],
    coins: 150,
    inventoryValue: 50,
    status: "",
    badges: [],
    anketa_about: "Замечаю детали которые другие пропускают",
    anketa_city: "Екб",
    anketa_interests: "Детали, красота, композиция",
    anketa_age: "20",
    anketa_looking_for: "Единомышленники",
    statusPool: ["", "Наблюдаю", "Анализирую", "Хм", "Интересно", "Замечаю"],
  },
  {
    socketId: "eE9fF0gG1hH2iI3jJ4kK",
    nickname: "Юля",
    characterType: "dog",
    gender: "female",
    eyeColor: "#00CED1",
    equipped: {
      shoes: { itemId: "shoes_sneakers", color: "#00CED1" },
      bottom: { itemId: "bottom_baggy", color: "#00CED1" },
    },
    ownedItems: ["shoes_sneakers", "bottom_baggy"],
    coins: 210,
    inventoryValue: 95,
    status: "",
    badges: ["messages_10"],
    anketa_about: "Много энергии, могу заразить позитивом",
    anketa_city: "Казань",
    anketa_interests: "Люди, развлечения, движение",
    anketa_age: "16",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Энергия", "Да!", "Привет", "Давай", "Активная"],
  },
  {
    socketId: "lL5mM6nN7oO8pP9qQ0rR",
    nickname: "Vova",
    characterType: "fox",
    gender: "male",
    eyeColor: "#7B68EE",
    equipped: { hats: { itemId: "hat_beanie", color: "#7B68EE" } },
    ownedItems: ["hat_beanie"],
    coins: 165,
    inventoryValue: 60,
    status: "",
    badges: ["first_friend"],
    anketa_about: "Живу своей жизнью, не люблю что критикуют",
    anketa_city: "Новосиб",
    anketa_interests: "Свое, искусство, выражение",
    anketa_age: "17",
    anketa_looking_for: "Поддержку",
    statusPool: ["", "Мой мир", "Не трогайте", "Вдохновение", "Я", "Себе"],
  },
  {
    socketId: "sS1tT2uU3vV4wW5xX6yY",
    nickname: "Полина",
    characterType: "cat",
    gender: "female",
    eyeColor: "#228B22",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#228B22" } },
    ownedItems: ["bottom_baggy"],
    coins: 120,
    inventoryValue: 40,
    status: "",
    badges: [],
    anketa_about: "Учусь и немного выгораю от этого",
    anketa_city: "Мск",
    anketa_interests: "Учеба, будущее, неизвестность",
    anketa_age: "18",
    anketa_looking_for: "Поддержка",
    statusPool: ["", "Школа", "Дома", "Не могу", "Помогите", "Уроки"],
  },
  {
    socketId: "zZ7aA8bB9cC0dD1eE2fF",
    nickname: "Andrew",
    characterType: "dog",
    gender: "male",
    eyeColor: "#FF4500",
    equipped: { hats: { itemId: "hat_cap", color: "#FF4500" } },
    ownedItems: ["hat_cap"],
    coins: 250,
    inventoryValue: 110,
    status: "",
    badges: ["messages_10", "first_message"],
    anketa_about: "Сидящий перед экраном, но не скучаю",
    anketa_city: "Спб",
    anketa_interests: "Экран, виртуальное, общение",
    anketa_age: "19",
    anketa_looking_for: "Общение",
    statusPool: ["", "Онлайн", "В сети", "Занят", "Не трогать", "Тут"],
  },
  {
    socketId: "gG3hH4iI5jJ6kK7lL8mM",
    nickname: "Светлана",
    characterType: "raccoon",
    gender: "female",
    eyeColor: "#BC8F8F",
    equipped: {
      shoes: { itemId: "shoes_boots", color: "#BC8F8F" },
      bottom: { itemId: "bottom_baggy", color: "#BC8F8F" },
    },
    ownedItems: ["shoes_boots", "bottom_baggy"],
    coins: 135,
    inventoryValue: 55,
    status: "",
    badges: [],
    anketa_about: "Люблю когда все аккуратно, порядок успокаивает",
    anketa_city: "Казань",
    anketa_interests: "Организация, красота, гармония",
    anketa_age: "17",
    anketa_looking_for: "Единомышленники",
    statusPool: ["", "Убираю", "Организую", "Спокойно", "Порядок", "Тихо"],
  },
  {
    socketId: "nN9oO0pP1qQ2rR3sS4tT",
    nickname: "Max",
    characterType: "panda",
    gender: "male",
    eyeColor: "#00008B",
    equipped: { hats: { itemId: "hat_cpcompany", color: "#00008B" } },
    ownedItems: ["hat_cpcompany"],
    coins: 190,
    inventoryValue: 75,
    status: "",
    badges: ["first_friend"],
    anketa_about: "Люблю прикол и веселье, жизнь одна",
    anketa_city: "Мск",
    anketa_interests: "Юмор, развлечение, дружба",
    anketa_age: "21",
    anketa_looking_for: "Веселье",
    statusPool: ["", "Смеюсь", "Классно", "О да", "Прикол", "Лол"],
  },
  {
    socketId: "uU5vV6wW7xX8yY9zZ0aA",
    nickname: "Надя",
    characterType: "fox",
    gender: "female",
    eyeColor: "#DC143C",
    equipped: {
      shoes: { itemId: "shoes_sneakers", color: "#DC143C" },
      bottom: { itemId: "bottom_baggy", color: "#DC143C" },
    },
    ownedItems: ["shoes_sneakers", "bottom_baggy"],
    coins: 270,
    inventoryValue: 120,
    status: "",
    badges: ["messages_10"],
    anketa_about: "Хочу видеть мир, жду когда вырасту",
    anketa_city: "Москва",
    anketa_interests: "Путешествия, приключения, новое",
    anketa_age: "16",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Мечтаю", "Хочу", "Может быть", "Интересно", "Скоро"],
  },
  {
    socketId: "bB1cC2dD3eE4fF5gG6hH",
    nickname: "Rita",
    characterType: "cat",
    gender: "female",
    eyeColor: "#FF69B4",
    equipped: { hats: { itemId: "hat_beanie", color: "#FF69B4" } },
    ownedItems: ["hat_beanie"],
    coins: 155,
    inventoryValue: 50,
    status: "",
    badges: [],
    anketa_about: "Живу по настроению, не люблю планы",
    anketa_city: "Екб",
    anketa_interests: "Спонтанность, веселье, неожиданность",
    anketa_age: "16",
    anketa_looking_for: "Приключение",
    statusPool: ["", "Не знаю", "Может быть", "Зависит", "По чувствам", "Время скажет"],
  },
  {
    socketId: "iI7jJ8kK9lL0mM1nN2oO",
    nickname: "Pavel",
    characterType: "dog",
    gender: "male",
    eyeColor: "#1C1C1C",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#1C1C1C" } },
    ownedItems: ["bottom_baggy"],
    coins: 220,
    inventoryValue: 90,
    status: "",
    badges: ["messages_10"],
    anketa_about: "Делаю что люблю, остальное не волнует",
    anketa_city: "Новосиб",
    anketa_interests: "Свои интересы, независимость, свобода",
    anketa_age: "23",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Занят", "Свое дело", "Не сейчас", "Может быть", "Смотрю"],
  },
  {
    socketId: "pP3qQ4rR5sS6tT7uU8vV",
    nickname: "Евгений",
    characterType: "fox",
    gender: "male",
    eyeColor: "#4169E1",
    equipped: { hats: { itemId: "hat_cap", color: "#4169E1" } },
    ownedItems: ["hat_cap"],
    coins: 280,
    inventoryValue: 130,
    status: "",
    badges: ["first_message"],
    anketa_about: "Люблю уходить в себя, но когда разговариваю то раскрываюсь",
    anketa_city: "Спб",
    anketa_interests: "Размышления, глубина, честность",
    anketa_age: "20",
    anketa_looking_for: "Глубокое общение",
    statusPool: ["", "Думаю", "Размышляю", "Слушаю", "Интересно", "Может"],
  },
  {
    socketId: "wW9xX0yY1zZ2aA3bB4cC",
    nickname: "Katya",
    characterType: "cat",
    gender: "female",
    eyeColor: "#800080",
    equipped: {
      bottom: { itemId: "bottom_baggy", color: "#800080" },
      shoes: { itemId: "shoes_boots", color: "#800080" },
    },
    ownedItems: ["bottom_baggy", "shoes_boots"],
    coins: 200,
    inventoryValue: 100,
    status: "",
    badges: ["first_friend"],
    anketa_about: "Экспрессивная, все переживаю остро",
    anketa_city: "Мск",
    anketa_interests: "Эмоции, чувства, выражение",
    anketa_age: "18",
    anketa_looking_for: "Понимание",
    statusPool: ["", "Чувствую", "Эмоции", "Ура", "Грусть", "Волнение"],
  },
  {
    socketId: "dD5eE6fF7gG8hH9iI0jJ",
    nickname: "Влад",
    characterType: "dog",
    gender: "male",
    eyeColor: "#A52A2A",
    equipped: { hats: { itemId: "hat_cpcompany", color: "#A52A2A" } },
    ownedItems: ["hat_cpcompany"],
    coins: 170,
    inventoryValue: 60,
    status: "",
    badges: [],
    anketa_about: "Расслабляюсь как могу, жизнь это не серьёз",
    anketa_city: "Казань",
    anketa_interests: "Развлечение, отдых, комфорт",
    anketa_age: "20",
    anketa_looking_for: "Тусовка",
    statusPool: ["", "Кайф", "Расслаб", "Не спешу", "Потом", "Может"],
  },
  {
    socketId: "kK1lL2mM3nN4oO5pP6qQ",
    nickname: "Ольга",
    characterType: "fox",
    gender: "female",
    eyeColor: "#3CB371",
    equipped: {
      shoes: { itemId: "shoes_boots", color: "#3CB371" },
      bottom: { itemId: "bottom_baggy", color: "#3CB371" },
    },
    ownedItems: ["shoes_boots", "bottom_baggy"],
    coins: 145,
    inventoryValue: 55,
    status: "",
    badges: [],
    anketa_about: "Люблю природу и свежий воздух, спасаюсь от города",
    anketa_city: "Владимир",
    anketa_interests: "Природа, спокойствие, простота",
    anketa_age: "19",
    anketa_looking_for: "Единомышленники",
    statusPool: ["", "На улице", "Воздух", "Спокойно", "Природа", "Отдых"],
  },
  {
    socketId: "rR7sS8tT9uU0vV1wW2xX",
    nickname: "Sergey",
    characterType: "panda",
    gender: "male",
    eyeColor: "#2F4F4F",
    equipped: { hats: { itemId: "hat_cap", color: "#2F4F4F" } },
    ownedItems: ["hat_cap"],
    coins: 230,
    inventoryValue: 100,
    status: "",
    badges: ["messages_10"],
    anketa_about: "Практичный парень, люблю детали",
    anketa_city: "Спб",
    anketa_interests: "Техника, процесс, результаты",
    anketa_age: "22",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Занят", "Работаю", "Процесс", "Результат", "Итог"],
  },
  {
    socketId: "yY3zZ4aA5bB6cC7dD8eE",
    nickname: "Инна",
    characterType: "fox",
    gender: "female",
    eyeColor: "#FF8C00",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#FF8C00" } },
    ownedItems: ["bottom_baggy"],
    coins: 180,
    inventoryValue: 70,
    status: "",
    badges: ["first_message"],
    anketa_about: "Хочу попробовать всё, любопытная от природы",
    anketa_city: "Новосиб",
    anketa_interests: "Опыт, новое, экспериментирование",
    anketa_age: "18",
    anketa_looking_for: "Приключение",
    statusPool: ["", "Интересно", "Пробую", "Новое", "А почему", "Попробуем"],
  },
  {
    socketId: "fF9gG0hH1iI2jJ3kK4lL",
    nickname: "Peter",
    characterType: "dog",
    gender: "male",
    eyeColor: "#8B7355",
    equipped: { hats: { itemId: "hat_cap", color: "#8B7355" } },
    ownedItems: ["hat_cap"],
    coins: 195,
    inventoryValue: 85,
    status: "",
    badges: [],
    anketa_about: "Люблю быть на свежем воздухе и в движении",
    anketa_city: "Тверь",
    anketa_interests: "Активность, воздух, простота",
    anketa_age: "25",
    anketa_looking_for: "Компания",
    statusPool: ["", "На улице", "Движение", "Лес", "Ветер", "Вперед"],
  },
  {
    socketId: "mM5nN6oO7pP8qQ9rR0sS",
    nickname: "Vitalina",
    characterType: "cat",
    gender: "female",
    eyeColor: "#F0E68C",
    equipped: {
      hats: { itemId: "hat_beanie", color: "#F0E68C" },
      shoes: { itemId: "shoes_sneakers", color: "#F0E68C" },
    },
    ownedItems: ["hat_beanie", "shoes_sneakers"],
    coins: 260,
    inventoryValue: 140,
    status: "",
    badges: ["messages_10", "first_friend"],
    anketa_about: "Смотрю на себя и мир критично, учусь быть лучше",
    anketa_city: "Мск",
    anketa_interests: "Самосовершенствование, понимание, путь",
    anketa_age: "17",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Развиваюсь", "Учусь", "Работаю", "Размышляю", "Вперед"],
  },
  {
    socketId: "tT1uU2vV3wW4xX5yY6zZ",
    nickname: "Igor",
    characterType: "raccoon",
    gender: "male",
    eyeColor: "#4B0082",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#4B0082" } },
    ownedItems: ["bottom_baggy"],
    coins: 140,
    inventoryValue: 50,
    status: "",
    badges: [],
    anketa_about: "Тихий, но с сильным внутренним миром",
    anketa_city: "Екб",
    anketa_interests: "Идеи, размышления, поиск",
    anketa_age: "20",
    anketa_looking_for: "Интересные люди",
    statusPool: ["", "Молчу", "Думаю", "Вопросы", "Ищу", "Понимаю"],
  },
  {
    socketId: "aA7bB8cC9dD0eE1fF2gG",
    nickname: "Оля",
    characterType: "fox",
    gender: "female",
    eyeColor: "#FF1493",
    equipped: {
      hats: { itemId: "hat_beanie", color: "#FF1493" },
      shoes: { itemId: "shoes_sneakers", color: "#FF1493" },
      bottom: { itemId: "bottom_baggy", color: "#FF1493" },
    },
    ownedItems: ["hat_beanie", "shoes_sneakers", "bottom_baggy"],
    coins: 300,
    inventoryValue: 160,
    status: "",
    badges: ["messages_10"],
    anketa_about: "Люблю выглядеть хорошо, за собой слежу",
    anketa_city: "Мск",
    anketa_interests: "Внешность, стиль, забота о себе",
    anketa_age: "17",
    anketa_looking_for: "Подруги",
    statusPool: ["", "Готовлюсь", "Красиво", "Вперед", "Звезда", "Люблю себя"],
  },
  {
    socketId: "hH3iI4jJ5kK6lL7mM8nN",
    nickname: "Kostya",
    characterType: "dog",
    gender: "male",
    eyeColor: "#20B2AA",
    equipped: { shoes: { itemId: "shoes_sneakers", color: "#20B2AA" } },
    ownedItems: ["shoes_sneakers"],
    coins: 165,
    inventoryValue: 60,
    status: "",
    badges: ["first_message"],
    anketa_about: "Всегда в деле, не люблю скуку",
    anketa_city: "Казань",
    anketa_interests: "Событие, движение, адреналин",
    anketa_age: "19",
    anketa_looking_for: "Друзья",
    statusPool: ["", "В деле", "Движусь", "Вперед", "Дай", "Скорость"],
  },
  {
    socketId: "oO9pP0qQ1rR2sS3tT4uU",
    nickname: "Tatiana",
    characterType: "panda",
    gender: "female",
    eyeColor: "#DC143C",
    equipped: { hats: { itemId: "hat_cap", color: "#DC143C" } },
    ownedItems: ["hat_cap"],
    coins: 210,
    inventoryValue: 90,
    status: "",
    badges: ["first_friend"],
    anketa_about: "Хочу общаться с разными людьми, учиться",
    anketa_city: "Спб",
    anketa_interests: "Люди, разнообразие, понимание",
    anketa_age: "18",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Общаюсь", "Слушаю", "Интересно", "Узнаю", "Спрашиваю"],
  },
  {
    socketId: "vV5wW6xX7yY8zZ9aA0bB",
    nickname: "Kirill",
    characterType: "cat",
    gender: "male",
    eyeColor: "#191970",
    equipped: { hats: { itemId: "hat_cpcompany", color: "#191970" } },
    ownedItems: ["hat_cpcompany"],
    coins: 190,
    inventoryValue: 75,
    status: "",
    badges: [],
    anketa_about: "Слушаю и анализирую, люблю разбираться в деталях",
    anketa_city: "Новосиб",
    anketa_interests: "Анализ, подробности, понимание",
    anketa_age: "21",
    anketa_looking_for: "Обсуждение",
    statusPool: ["", "Слушаю", "Анализирую", "Интересно", "Подробнее", "Понимаю"],
  },
  {
    socketId: "cC1dD2eE3fF4gG5hH6iI",
    nickname: "Dima",
    characterType: "dog",
    gender: "male",
    eyeColor: "#2C3E50",
    equipped: { shoes: { itemId: "shoes_sneakers", color: "#2C3E50" } },
    ownedItems: ["shoes_sneakers"],
    coins: 155,
    inventoryValue: 45,
    status: "",
    badges: [],
    anketa_about: "Простой парень, разговорчивый",
    anketa_city: "Мск",
    anketa_interests: "Общение, простота, люди",
    anketa_age: "17",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Привет", "Как дела", "Говорю", "Слушаю", "Норм"],
  },
  {
    socketId: "jJ2kK3lL4mM5nN6oO7pP",
    nickname: "Vika",
    characterType: "fox",
    gender: "female",
    eyeColor: "#E74C3C",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#E74C3C" } },
    ownedItems: ["bottom_baggy"],
    coins: 175,
    inventoryValue: 65,
    status: "",
    badges: ["first_message"],
    anketa_about: "Люблю шутки и смех, не люблю скучных людей",
    anketa_city: "Казань",
    anketa_interests: "Юмор, веселье, позитив",
    anketa_age: "15",
    anketa_looking_for: "Веселую компанию",
    statusPool: ["", "Смеюсь", "Прикол", "Ха", "О да", "Класс"],
  },
  {
    socketId: "qQ3rR4sS5tT6uU7vV8wW",
    nickname: "Artem",
    characterType: "raccoon",
    gender: "male",
    eyeColor: "#27AE60",
    equipped: { hats: { itemId: "hat_cap", color: "#27AE60" } },
    ownedItems: ["hat_cap"],
    coins: 200,
    inventoryValue: 95,
    status: "",
    badges: [],
    anketa_about: "Мечтаю что-то достичь, но пока не знаю что",
    anketa_city: "Екб",
    anketa_interests: "Цели, развитие, неопределенность",
    anketa_age: "18",
    anketa_looking_for: "Поддержка",
    statusPool: ["", "Думаю", "Помечтаю", "Может быть", "Вот бы", "Когда-нибудь"],
  },
  {
    socketId: "xX5yY6zZ7aA8bB9cC0dD",
    nickname: "Zhenya",
    characterType: "fox",
    gender: "female",
    eyeColor: "#3498DB",
    equipped: { shoes: { itemId: "shoes_boots", color: "#3498DB" } },
    ownedItems: ["shoes_boots"],
    coins: 140,
    inventoryValue: 48,
    status: "",
    badges: [],
    anketa_about: "Тихая, но если открыться то много интересного",
    anketa_city: "Спб",
    anketa_interests: "Внутренний мир, доверие, связь",
    anketa_age: "16",
    anketa_looking_for: "Своих людей",
    statusPool: ["", "Молчу", "Наблюдаю", "Если...", "Может быть", "Интересно"],
  },
  {
    socketId: "eE6fF7gG8hH9iI0jJ1kK",
    nickname: "Timur",
    characterType: "panda",
    gender: "male",
    eyeColor: "#F39C12",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#F39C12" } },
    ownedItems: ["bottom_baggy"],
    coins: 190,
    inventoryValue: 85,
    status: "",
    badges: ["messages_10"],
    anketa_about: "Живу моментом, не люблю сложности",
    anketa_city: "Мск",
    anketa_interests: "Простота, радость, здесь-сейчас",
    anketa_age: "19",
    anketa_looking_for: "Компания",
    statusPool: ["", "Кайф", "Сейчас", "Настроение", "Классно", "Давай"],
  },
  {
    socketId: "lL8mM9nN0oO1pP2qQ3rR",
    nickname: "Marina",
    characterType: "cat",
    gender: "female",
    eyeColor: "#9B59B6",
    equipped: {
      hats: { itemId: "hat_beanie", color: "#9B59B6" },
      shoes: { itemId: "shoes_sneakers", color: "#9B59B6" },
    },
    ownedItems: ["hat_beanie", "shoes_sneakers"],
    coins: 220,
    inventoryValue: 110,
    status: "",
    badges: [],
    anketa_about: "Ищу себя еще, может быть тут найду",
    anketa_city: "Новосиб",
    anketa_interests: "Поиск, самооткрытие, развитие",
    anketa_age: "17",
    anketa_looking_for: "Помощь",
    statusPool: ["", "Ищу", "Думаю", "Может быть", "Не знаю", "Помогите"],
  },
  {
    socketId: "sS9tT0uU1vV2wW3xX4yY",
    nickname: "Stas",
    characterType: "dog",
    gender: "male",
    eyeColor: "#34495E",
    equipped: { hats: { itemId: "hat_cp", color: "#34495E" } },
    ownedItems: ["hat_cap"],
    coins: 165,
    inventoryValue: 55,
    status: "",
    badges: ["first_message"],
    anketa_about: "Спокойный, не люблю много говорить",
    anketa_city: "Казань",
    anketa_interests: "Спокойствие, мир, простота",
    anketa_age: "20",
    anketa_looking_for: "Друзья",
    statusPool: ["", "Спокойно", "Все хорошо", "Может быть", "Норм", "Ок"],
  },
  {
    socketId: "zZ0aA1bB2cC3dD4eE5fF",
    nickname: "Nastya",
    characterType: "fox",
    gender: "female",
    eyeColor: "#C0504D",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#C0504D" } },
    ownedItems: ["bottom_baggy"],
    coins: 185,
    inventoryValue: 80,
    status: "",
    badges: [],
    anketa_about: "Люблю делиться и помогать, жалею всех",
    anketa_city: "Спб",
    anketa_interests: "Люди, чувства, помощь",
    anketa_age: "16",
    anketa_looking_for: "Тех кому нужна помощь",
    statusPool: ["", "Помогаю", "Слушаю", "Переживаю", "Жалею", "Забочусь"],
  },
  {
    socketId: "gG1hH2iI3jJ4kK5lL6mM",
    nickname: "Ivan",
    characterType: "dog",
    gender: "male",
    eyeColor: "#70AD47",
    equipped: { shoes: { itemId: "shoes_boots", color: "#70AD47" } },
    ownedItems: ["shoes_boots"],
    coins: 195,
    inventoryValue: 75,
    status: "",
    badges: [],
    anketa_about: "Люблю приключения и новый опыт",
    anketa_city: "Екб",
    anketa_interests: "Приключение, новое, опыт",
    anketa_age: "18",
    anketa_looking_for: "Товарищей",
    statusPool: ["", "Авантюра", "Вперед", "Новое", "Опыт", "Пошли"],
  },
  {
    socketId: "nN7oO8pP9qQ0rR1sS2tT",
    nickname: "Sofya",
    characterType: "fox",
    gender: "female",
    eyeColor: "#4472C4",
    equipped: { hats: { itemId: "hat_beanie", color: "#4472C4" } },
    ownedItems: ["hat_beanie"],
    coins: 155,
    inventoryValue: 65,
    status: "",
    badges: ["first_friend"],
    anketa_about: "Романтичная, верю в хорошее",
    anketa_city: "Мск",
    anketa_interests: "Романтика, мечты, красота",
    anketa_age: "15",
    anketa_looking_for: "Душевное общение",
    statusPool: ["", "Мечтаю", "Верю", "Красиво", "Волшебство", "Чудо"],
  },
  {
    socketId: "uU3vV4wW5xX6yY7zZ8aA",
    nickname: "Constantine",
    characterType: "panda",
    gender: "male",
    eyeColor: "#FFC000",
    equipped: { bottom: { itemId: "bottom_baggy", color: "#FFC000" } },
    ownedItems: ["bottom_baggy"],
    coins: 210,
    inventoryValue: 95,
    status: "",
    badges: [],
    anketa_about: "Люблю смеяться над собой, не беру всё всерьез",
    anketa_city: "Новосиб",
    anketa_interests: "Юмор, забава, легкость",
    anketa_age: "20",
    anketa_looking_for: "Компанию",
    statusPool: ["", "Улыбка", "Прикол", "Не серьез", "Веселье", "Забава"],
  },
  {
    socketId: "bB4cC5dD6eE7fF8gG9hH",
    nickname: "Daria",
    characterType: "cat",
    gender: "female",
    eyeColor: "#A64D79",
    equipped: {
      shoes: { itemId: "shoes_sneakers", color: "#A64D79" },
      bottom: { itemId: "bottom_baggy", color: "#A64D79" },
    },
    ownedItems: ["shoes_sneakers", "bottom_baggy"],
    coins: 175,
    inventoryValue: 70,
    status: "",
    badges: [],
    anketa_about: "Люблю говорить о чувствах и отношениях",
    anketa_city: "Казань",
    anketa_interests: "Чувства, дружба, глубина",
    anketa_age: "17",
    anketa_looking_for: "Своих",
    statusPool: ["", "Разговор", "Чувства", "Честно", "Серьезно", "Душевно"],
  },
  {
    socketId: "iI0jJ1kK2lL3mM4nN5oO",
    nickname: "Alex",
    characterType: "dog",
    gender: "male",
    eyeColor: "#595959",
    equipped: { hats: { itemId: "hat_cap", color: "#595959" } },
    ownedItems: ["hat_cap"],
    coins: 235,
    inventoryValue: 105,
    status: "",
    badges: ["messages_10"],
    anketa_about: "Жизнь это путешествие, главное процесс",
    anketa_city: "Спб",
    anketa_interests: "Жизнь, путь, развитие",
    anketa_age: "22",
    anketa_looking_for: "Друзья",
    statusPool: ["", "В пути", "В процессе", "Развиваюсь", "Живу", "Путь"],
  },
  {
    socketId: "pP6qQ7rR8sS9tT0uU1vV",
    nickname: "Elena",
    characterType: "raccoon",
    gender: "female",
    eyeColor: "#FF0000",
    equipped: { shoes: { itemId: "shoes_boots", color: "#FF0000" } },
    ownedItems: ["shoes_boots"],
    coins: 150,
    inventoryValue: 60,
    status: "",
    badges: [],
    anketa_about: "Люблю смотреть на людей и понимать их",
    anketa_city: "Екб",
    anketa_interests: "Люди, психология, наблюдение",
    anketa_age: "19",
    anketa_looking_for: "Интересные люди",
    statusPool: ["", "Наблюдаю", "Анализирую", "Интересно", "Понимаю", "Вижу"],
  },
];
